[influxdb]

host = "127.0.0.1"
port = "8086"
db = "smokeping_db"
measurement = "ping"
user = "admin"
pass = "admin5Up3RSecr3tP4aSsW0rd4GhL6AzXf"

[hosts]

hosts = [
    "127.0.0.1",
    "8.8.8.8",
    "itb.ac.id"
]
