[influxdb]

host = "192.168.114.30"
port = "8086"
db = "fping"
measurement = "ping"
user = "fping"
pass = "fpingd18071702c48"

[hosts]

hosts = [
    "localhost",
    "bukalapak.com",
    "udx.web.id"
]
